### ISSUE TITLE
Notification not displaying

### ISSUE THREAD

**Issue by romanzipp** [andreyviktorov/notiny#6]
I am using Notiny with Semantic-UI, but no notification is displaying at all.

When triggering `$.notiny()` no `<div class="notiny" />` is appended to the body, although defined in `notiny.js`:

``` js
$notiny = $('<div class="notiny" />').appendTo($('body'));
```

All files are getting loaded correctly and no errors appear in the dev console.

Also, the `$.notiny` event is triggered after initializing JQuery and the `<body>` is present.

**JQuery:** 2.1.4
**JQuery UI:** 1.11.4
**Semantic-UI:** 2.2

**Comment by 4ndv** [comment]
Could you put notiny script before body closing tag or show your page structure?

**Comment by romanzipp** [comment]
I put the script tag in the `<head>` section, moving it to the end of `<body>` resolved the issue. Thanks!

**Comment by 4ndv** [comment]
Glad it helped you! :)
